import Head from 'next/head'
import { Navbar } from '../Navbar'

type Props = {
  children?: JSX.Element | JSX.Element[];
}

export const MainLayout = ({ children }: Props) => {
  return (
    <div className={'container'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={'main'}>
        {children}
      </main>
    </div>
  )
}
